export enum TableHeaderTypeEnum {
  TEXT = 'text',
  DATE = 'date',
  TIME = 'time',
  EMAIL = 'email',
  IMAGE = 'image',
  STRING = 'string',
  NUMBER = 'number',
  STATUS = 'status',
  AVATAR = 'avatar',
  SLUGGED = 'slugged',
  PROGRESS = 'progress',
  FEATURED = 'featured',
  CURRENCY = 'currency',
  LONG_TEXT = 'long-text',
  PUBLISHED = 'published',
  DATE_TIME = 'date-time',
}